apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2  # Increased to 2 for high availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0       # Ensure at least 1 pod stays available
      maxSurge: 1             # Allow 1 extra pod during update
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: bhonebhone/simple-nodejs-app:latest
          imagePullPolicy: Always  # Always pull latest image
          ports:
            - containerPort: 3000
