apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: nodejs-app-ns  # ✅ Specify the namespace here
spec:
  replicas: 2  # High availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0       # Ensure no downtime
      maxSurge: 1             # Allow 1 extra pod during update
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: bhonebhone/simple-nodejs-app:823070b
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

