apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000           # Service port
      targetPort: 3000     # Container port
      nodePort: 32000      # External access via <NodeIP>:32000
