<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000           # Service port
      targetPort: 3000     # Container port
      nodePort: 32000      # External access via <NodeIP>:32000
=======
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
>>>>>>> 2fcd26131d56968b64d5b6e37756494e8cd873e0
